export const events = [
  {
    title: "DevFest Nairobi 2026",
    slug: "devfest-nairobi-2026",
    location: "Sarit Expo Centre, Nairobi",
    date: "2026-10-15",
    time: "09:00 AM",
    image: "/images/devfest.jpg",
    description: "The largest Google Developer Group event in Kenya featuring talks on Android, Web, and Cloud.",
  },
  {
    title: "PyCon Kenya",
    slug: "pycon-kenya",
    location: "USIU Africa, Nairobi",
    date: "2026-09-22",
    time: "08:30 AM",
    image: "/images/pycon.jpg",
    description: "Annual gathering of the Python community in Kenya. Workshops, talks, and networking.",
  },
  {
    title: "React Kenya Meetup",
    slug: "react-kenya-meetup",
    location: "iHub, Nairobi",
    date: "2026-11-05",
    time: "05:00 PM",
    image: "/images/react.jpg",
    description: "Deep dive into React 19, Server Components, and the future of the frontend web.",
  },
  {
    title: "AWS Community Day",
    slug: "aws-community-day-kenya",
    location: "Radisson Blu, Nairobi",
    date: "2026-08-20",
    time: "09:00 AM",
    image: "/images/aws.jpg",
    description: "Cloud computing conference run by the AWS community for the community.",
  },
  {
    title: "Africa Hackon",
    slug: "africa-hackon",
    location: "KICC, Nairobi",
    date: "2026-12-01",
    time: "08:00 AM",
    image: "/images/hackon.jpg",
    description: "East Africa's premier cyber security conference showcasing the latest in infosec.",
  },
  {
    title: "Nairobi Tech Week",
    slug: "nairobi-tech-week",
    location: "Strathmore University",
    date: "2027-02-14",
    time: "10:00 AM",
    image: "/images/techweek.jpg",
    description: "A week-long celebration of technology and innovation in Sub-Saharan Africa.",
  },
  {
    title: "Women Techmakers",
    slug: "wtm-nairobi",
    location: "Nairobi Garage",
    date: "2027-03-08",
    time: "09:00 AM",
    image: "/images/wtm.jpg",
    description: "Empowering women in technology through networking, mentorship, and technical workshops.",
  },
  {
    title: "Flutter Kenya Hackathon",
    slug: "flutter-kenya-hackathon",
    location: "ALX Hub, Nairobi",
    date: "2026-09-10",
    time: "08:00 AM",
    image: "/images/flutter.jpg",
    description: "A 48-hour hackathon building cross-platform apps using Flutter and Firebase.",
  },
  {
    title: "Blockchain Developers",
    slug: "blockchain-nairobi",
    location: "The Mint Hub, Nairobi",
    date: "2026-10-02",
    time: "02:00 PM",
    image: "/images/blockchain.jpg",
    description: "Explore Web3, smart contracts, and decentralized applications on Ethereum and Solana.",
  },
  {
    title: "Kotlin Kenya Meetup",
    slug: "kotlin-kenya",
    location: "Microsoft ADC, Nairobi",
    date: "2026-11-20",
    time: "06:00 PM",
    image: "/images/kotlin.jpg",
    description: "Learn about Kotlin Multiplatform and modern Android development practices.",
  },
  {
    title: "Data Science Africa",
    slug: "dsa-nairobi",
    location: "Dedan Kimathi University",
    date: "2027-04-10",
    time: "09:00 AM",
    image: "/images/datascience.jpg",
    description: "Advancing AI and Data Science capacity in Africa with hands-on machine learning sessions.",
  },
  {
    title: "CyberSec Kenya",
    slug: "cybersec-kenya",
    location: "Kenyatta University",
    date: "2026-08-30",
    time: "09:00 AM",
    image: "/images/cybersec.jpg",
    description: "Learn defensive and offensive security strategies from industry experts.",
  },
];
